name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          cd app
          docker build -t dast-automation-web .

      - name: Run Flask app in Docker
        run: |
          cd app
          docker run -d -p 8080:8080 --name dast-automation-web dast-automation-web
          sleep 30  # Wait for the application to be ready

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Pull OWASP ZAP Docker image
        run: docker pull ictu/zap2docker-weekly

      - name: Start OWASP ZAP scan
        run: |
          sudo chmod -R 777 $(pwd)  # Ensure the directory has the correct permissions
          docker run -v $(pwd):/zap/wrk/:rw -t ictu/zap2docker-weekly zap-baseline.py -t http://host.docker.internal:8080 -r zap_report.html

      - name: Stop Docker container
        run: |
          docker stop dast-automation-web
          docker rm dast-automation-web

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
