name: OWASP ZAP DAST Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start Application
        run: |
          docker-compose up -d
          sleep 10  # Tunggu agar aplikasi siap

      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: "http://localhost:8080"
          fail_action: false
          cmd_options: "-a"

      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report.json

      - name: Analyze Scan Report
        run: |
          if grep -q '"risk":"High"' report.json; then
            echo "High-risk vulnerabilities found!"
            exit 1
          else
            echo "No high-risk vulnerabilities found."
          fi
