name: DAST Automation

on:
  push:
    branches:
      - main

jobs:
  dast-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run Flask app
        run: |
          docker build -t dast-automation-web .
          docker run -d -p 8081:8081 --name dast-automation-web dast-automation-web
          sleep 10  # Tunggu aplikasi siap

      - name: Run OWASP ZAP Scan
        run: |
          docker run --network=host -v $(pwd):/zap/wrk -t owasp/zap2docker-stable zap-baseline.py -t http://localhost:8081 -r zap_report.html

      - name: Upload OWASP ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html
