name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          cd app
          docker build -t dast-automation-web .

      - name: Run Flask app in Docker
        run: |
          cd app
          docker run -d -p 8080:8080 --name dast-automation-web dast-automation-web
          sleep 10  # Wait for the application to be ready

      - name: Install OWASP ZAP CLI
        run: |
          curl -sSL https://github.com/zaproxy/zaproxy/releases/download/v2.11.0/zap-2.11.0-linux.tar.gz | tar -xz
          export ZAP_HOME=$(pwd)/zap-2.11.0
          export PATH=$ZAP_HOME:$PATH

      - name: Start OWASP ZAP scan
        run: |
          zap-cli quick-scan --self-contained --start-url http://localhost:8081

      - name: Stop Docker container
        run: |
          docker stop dast-automation-web
